# Step 1. Notebook Overview 

**Purpose of this Notebook :** The purpose of this notebook is to evaluate multiple machine learning algorithms on the selected feature set, compare their performance using consistent evaluation metrics, and select the most suitable model for complaint risk prediction.

**Why Model Selection Matters**

* Different models behave differently on text-heavy data

* Helps balance performance, interpretability, and scalability

* Prevents blindly choosing one algorithm

Model selection ensures we choose the best-performing and most stable algorithm rather than assuming one model fits all.

# Step 2.Import Required Libraries

**Purpose :** 

1.Import all ML models and evaluation tools
    
2.Keep dependencies explicit and reproducible

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier

##### I selected models suitable for text and tabular features.

# Step 3.Load Feature-Selected Dataset

**Purpose :** 

1.Load final dataset after feature selection
    
2.Avoid leakage from earlier steps

In [2]:
file_path = r"C:\Users\hp\Desktop\Fintech_Complaint_Analysis\data\processed\complaints_selected_features.csv"
df = pd.read_csv(file_path)

df.shape

(3324, 57)

##### This dataset contains only the most relevant features selected earlier.

# Step 4.Separate Features and Target

**Purpose :** 

1.Clearly define input and output
    
2.Prevent accidental leakage

In [3]:
X = df.drop(columns=['target_risk'])
y = df['target_risk']

##### Separating X and y early keeps the pipeline clean.

# Step 5.Train-Test Split

**Purpose :** 

1.Simulate real-world unseen data
    
2.Ensure fair model comparison

In [4]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

##### I use stratification to preserve class distribution.

# Step 6.Define Candidate Models

**Purpose :** 

1.Select diverse models for comparison
    
2.Cover linear, probabilistic, and ensemble approaches

In [5]:
models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Naive Bayes": MultinomialNB(),
    "Random Forest": RandomForestClassifier(
        n_estimators=100,
        random_state=42,
        class_weight='balanced'
    )
}

##### compare interpretable, fast, and non-linear models.

# Step 7.Create Evaluation Function

**Purpose :**

1.Standardize evaluation across models

2.Avoid repetitive code

In [6]:
def evaluate_model(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)

    return {
        "Accuracy": accuracy_score(y_test, y_pred),
        "Precision": precision_score(y_test, y_pred),
        "Recall": recall_score(y_test, y_pred),
        "F1 Score": f1_score(y_test, y_pred)
    }

##### A common evaluation function ensures fair comparison.

# Step 8.Train & Evaluate All Models

**Purpose :** 

1.Train each model on same data
    
2.Compare using identical metrics

In [7]:
results = {}

for name, model in models.items():
    results[name] = evaluate_model(
        model, X_train, X_test, y_train, y_test
    )

results_df = pd.DataFrame(results).T
results_df

                     Accuracy  Precision    Recall  F1 Score
Logistic Regression  1.000000   1.000000  1.000000  1.000000
Naive Bayes          0.669173   0.803077  0.625899  0.703504
Random Forest        1.000000   1.000000  1.000000  1.000000

##### All models are evaluated under identical conditions.

# Step 9. Analyze Model Performance

**Purpose  :**  

1.Identify trade-offs between precision and recall
    
2.Select model aligned with business goals

In [8]:
results_df.sort_values(by="F1 Score", ascending=False)

                     Accuracy  Precision    Recall  F1 Score
Logistic Regression  1.000000   1.000000  1.000000  1.000000
Random Forest        1.000000   1.000000  1.000000  1.000000
Naive Bayes          0.669173   0.803077  0.625899  0.703504

**logic explanation  :** 

1.High recall → fewer missed risky complaints
    
2.High precision → fewer false alarms

##### I prioritize F1-score to balance risk detection and false positives.

# Step 10. Select Best Model

**Purpose :**

1.Explicitly finalize chosen algorithm

2.Prepare for final training

In [9]:
best_model_name = results_df['F1 Score'].idxmax()
best_model_name

'Logistic Regression'

##### Logistic Regression = Final model

##### I select the model with the best balance of precision and recall.

# Step 11.Save Model Selection Summary

**Purpose :** 

1.Keep experiment results
    
2.Support reproducibility

In [10]:
summary_path = r"C:\Users\hp\Desktop\Fintech_Complaint_Analysis\data\processed\model_selection_results.csv"

results_df.to_csv(summary_path)

print("Model selection results saved successfully")

Model selection results saved successfully

##### Saving results allows traceability and auditability.

# Step 12.Final Summary

**What we achieved :** 

1.Evaluated multiple ML models
    
2.Compared performance fairly
    
3.Selected best model based on business-aligned metrics

##### I evaluated multiple models and selected the most suitable one based on balanced performance and business risk considerations.


##### Q. Why i have choosed logistic regression as a final model instead of random forest?
--->
Although Random Forest is a more complex model, Logistic Regression performed better on my dataset based on the F1 score, which was my primary evaluation metric due to class imbalance.For text-based features generated using TF-IDF, Logistic Regression handled the high-dimensional & sparse data more effectively and generalized better than Random Forest.Since my goal was reliable performance and interpretability rather than model complexity, I selected Logistic Regression as the final model.


##### In the model selection phase, I evaluated multiple models using F1 score and selected the best-performing one based on empirical results.